### ISSUE TITLE
Beginner level

### ISSUE THREAD

**Issue by kaushalkoladiya** [kaushalkoladiya/twitter-clone-frontend#2]
#### Do the inverse of method "push()".

- Hint:
  - The **push** function will add value at the end of the array. In this case you have do it's inverse.
- Rules
  - Only a single line change will be allowed.
  - No new line will be allowed.

```
var arr = [12, 45, 67, 23, 78];
arr.push(100);
console.log(arr);
// Current Output: [12, 45, 67, 23, 78, 100]
// Expected Output: [100, 12, 45, 67, 23, 78]
```

#### Inverse of the output.

- Hint:

  - **x** and **y** are declared using **_const_**. So, you cannot modify it's value.

- Rules
  - You cannot chnage variable's datatype.
  - One new line will be allowed.
  - You cannot changes the comparison operator

```
const x = [];
const y = 1;

console.log(x == y);
// Current Output: false
// Expected Output: true
```

#### Variable's scope

- Rules
  - No new line will be allowed.

```
var a = 10;
function foo () {
    var a = 20;
    console.log(a);
}

foo();
// Current Output: 20
// Exprected Output: 10
```

#### Array's value

- Rules
  - Cannot allowed this approach **fruits[i]**.
  - No new line will be allowed.
  - Only a single line change will be allowed.

```
var fruits = ['Lemon', 'Pomelo', 'Kumquat', 'Yuzu', 'Blood orange'];

for(i in fruits) {
    console.log(i);
}
/*
Current Output:
0
1
2
3
4

Expected Output:
Lemon
Pomelo
Kumquat
Yuzu
Blood orange
*/
```

#### Fix the bug

- Hint:
  - Find **is** from the given String.
- Rules
  - No new line will be allowed.

```
var str = "This is JavaScript";
str.findIndex("is");
```

**Comment by krishita30j** [comment]
I would like to work on this issue. Can I proceed?

**Comment by deepesh-ludhyani** [comment]
I would like to work on this issue

**Comment by kaushalkoladiya** [comment]
> I would like to work on this issue. Can I proceed?
> 

Yes you can

**Comment by kaushalkoladiya** [comment]
> I would like to work on this issue

Go ahead
